Repository CodeDredd/pinia-orm, pull requests merged in 2022-07, with the labels that each got.

#17 feat(#16): Pass pinia options via model property
  packages/pinia-orm/src/composables/useDataStore.ts
  packages/pinia-orm/src/connection/Connection.ts
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/tests/feature/repository/save.spec.ts
  packages/pinia-orm/tests/unit/model/Model_pinia_options.spec.ts
Labels: enhancement

#79 feat(pinia-orm): add belongsToMany relation function
  docs/content/2.model/3.decorators.md
  docs/content/3.relationships/4.many-to-many.md
  docs/content/3.relationships/5.polymorphic.md
  package.json
  packages/nuxt/package.json
  packages/pinia-orm/package.json
  packages/pinia-orm/src/index.cjs.ts
  packages/pinia-orm/src/index.ts
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/model/attributes/relations/BelongsToMany.ts
  packages/pinia-orm/src/model/attributes/relations/Relation.ts
  packages/pinia-orm/src/model/decorators/attributes/relations/BelongsToMany.ts
  packages/pinia-orm/src/store/Store.ts
  packages/pinia-orm/tests/feature/relations/belongs_to_many_retrieve.spec.ts
  packages/pinia-orm/tests/feature/relations/belongs_to_many_save.spec.ts
  packages/pinia-orm/tests/feature/relations/belongs_to_many_save_custom_key.spec.ts
  pnpm-lock.yaml
Labels: enhancement

#84 feat(pinia-orm): add mutators
  docs/content/2.model/2.accessors.md
  docs/content/2.model/3.decorators.md
  packages/pinia-orm/src/index.cjs.ts
  packages/pinia-orm/src/index.ts
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/model/decorators/Mutate.ts
  packages/pinia-orm/src/query/Query.ts
  packages/pinia-orm/src/types/index.ts
  packages/pinia-orm/tests/unit/model/Model_Mutators.spec.ts
  packages/pinia-orm/tsconfig.json
Labels: enhancement

#91 feat(pinia-orm): add life-cycle-hooks
  docs/content/2.model/4.lifecycle-hooks.md
  docs/content/2.model/5.pinia-options.md
  packages/pinia-orm/src/connection/Connection.ts
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/query/Query.ts
  packages/pinia-orm/src/repository/Repository.ts
  packages/pinia-orm/tests/feature/hooks/created.spec.ts
  packages/pinia-orm/tests/feature/hooks/creating.spec.ts
  packages/pinia-orm/tests/feature/hooks/deleted.spec.ts
  packages/pinia-orm/tests/feature/hooks/deleting.spec.ts
  packages/pinia-orm/tests/feature/hooks/saved.spec.ts
  packages/pinia-orm/tests/feature/hooks/saving.spec.ts
  packages/pinia-orm/tests/feature/hooks/updated.spec.ts
  packages/pinia-orm/tests/feature/hooks/updating.spec.ts
  packages/pinia-orm/tests/unit/repository/Repository.spec.ts
Labels: enhancement

#118 fix(pinia-orm): belongsToMany was behaving incorrectly nested
  packages/pinia-orm/src/model/attributes/relations/BelongsToMany.ts
  packages/pinia-orm/tests/feature/relations/belongs_to_many_save_custom_key.spec.ts
Labels: bug

#120 fix: typo - misspelled pinia for pina
  docs/content/1.index.md
Labels: documentation

#131 fix(pinia-orm): A few Query methods have wrong return type
  packages/pinia-orm/src/query/Query.ts
Labels: bug

#117 feat(pinia-orm): Add single table inheritance support
  docs/content/1.guide/2.model/7.single-table-inheritance.md
  docs/content/2.api/2.model/3.base-entity.md
  docs/content/2.api/2.model/3.typeKey.md
  docs/content/2.api/2.model/3.types.md
  packages/pinia-orm/src/composables/useRepo.ts
  packages/pinia-orm/src/database/Database.ts
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/query/Query.ts
  packages/pinia-orm/tests/unit/model/Model_STI.spec.ts
Labels: enhancement
