Repository CodeDredd/pinia-orm, pull requests merged in 2022-10, with the labels that each got.

#438 fix(pinia-orm): pivot are not correctly loaded
  README.md
  packages/nuxt/.nuxtrc
  packages/nuxt/build.config.ts
  packages/nuxt/package.json
  packages/nuxt/playground/nuxt.config.ts
  packages/pinia-orm/package.json
  packages/pinia-orm/src/model/attributes/relations/BelongsToMany.ts
  packages/pinia-orm/tests/feature/relations/belongs_to_many_retrieve.spec.ts
  pnpm-lock.yaml
Labels: bug

#482 docs: orderBy was used in documentation for chaining groupBy
  docs/content/1.guide/4.repository/2.retrieving-data.md
Labels: documentation

#491 feat(pinia-orm): add `record` to saving hooks
  docs/content/1.guide/2.model/5.lifecycle-hooks.md
  docs/content/2.api/2.model/4.hooks/created.md
  docs/content/2.api/2.model/4.hooks/creating.md
  docs/content/2.api/2.model/4.hooks/saved.md
  docs/content/2.api/2.model/4.hooks/saving.md
  docs/content/2.api/2.model/4.hooks/updated.md
  docs/content/2.api/2.model/4.hooks/updating.md
  packages/pinia-orm/src/index.ts
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/model/attributes/relations/BelongsTo.ts
  packages/pinia-orm/src/model/attributes/relations/HasMany.ts
  packages/pinia-orm/src/model/attributes/relations/HasManyBy.ts
  packages/pinia-orm/src/model/attributes/relations/HasOne.ts
  packages/pinia-orm/src/model/attributes/relations/MorphMany.ts
  packages/pinia-orm/src/model/attributes/relations/MorphOne.ts
  packages/pinia-orm/src/model/attributes/relations/MorphTo.ts
  packages/pinia-orm/src/model/attributes/relations/Relation.ts
  packages/pinia-orm/src/query/Query.ts
  packages/pinia-orm/tests/feature/hooks/saving.spec.ts
Labels: enhancement
