Repository CodeDredd/pinia-orm, pull requests merged in 2022-11, with the labels that each got.

#529 feat(pinia-orm): Add the possibility to delete by cascade
  docs/content/1.guide/2.model/2.accessors.md
  docs/content/1.guide/2.model/3.casts.md
  docs/content/1.guide/2.model/4.decorators.md
  docs/content/1.guide/2.model/7.single-table-inheritance.md
  docs/content/1.guide/3.relationships/1.getting-started.md
  docs/content/2.api/3.query/delete.md
  docs/content/2.api/3.query/destroy.md
  packages/pinia-orm/src/decorators.ts
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/model/attributes/relations/Relation.ts
  packages/pinia-orm/src/model/decorators/OnDelete.ts
  packages/pinia-orm/src/query/Query.ts
  packages/pinia-orm/tests/feature/repository/delete_with_relations.spec.ts
  packages/pinia-orm/tests/unit/support/Utils.spec.ts
Labels: enhancement

#544 feat(pinia-orm): Attributes can now accept closures for default value
  docs/content/1.guide/2.model/1.getting-started.md
  docs/content/2.api/2.model/1.fields-attributes/attr.md
  docs/content/2.api/2.model/1.fields-attributes/boolean.md
  docs/content/2.api/2.model/1.fields-attributes/number.md
  docs/content/2.api/2.model/1.fields-attributes/string.md
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/model/attributes/types/Boolean.ts
  packages/pinia-orm/src/model/attributes/types/Number.ts
  packages/pinia-orm/src/model/attributes/types/String.ts
  packages/pinia-orm/src/model/attributes/types/Type.ts
  packages/pinia-orm/src/model/decorators/attributes/types/Attr.ts
  packages/pinia-orm/src/model/decorators/attributes/types/Bool.ts
  packages/pinia-orm/src/model/decorators/attributes/types/Num.ts
  packages/pinia-orm/src/model/decorators/attributes/types/Str.ts
  packages/pinia-orm/tests/unit/model/Model_Attrs_String.spec.ts
Labels: enhancement

#546 feat(pinia-orm): Add simple `DateCast`
  docs/content/1.guide/2.model/3.casts.md
  docs/content/2.api/2.model/3.casts.md
  packages/pinia-orm/src/casts.ts
  packages/pinia-orm/src/model/casts/CastAttribute.ts
  packages/pinia-orm/src/model/casts/DateCast.ts
  packages/pinia-orm/tests/unit/model/Model_Casts_Date.spec.ts
Labels: enhancement

#555 fix(pinia-orm): using childRepo (STI) for saving without type defined
  docs/content/1.guide/2.model/7.single-table-inheritance.md
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/model/attributes/types/Type.ts
  packages/pinia-orm/src/query/Query.ts
  packages/pinia-orm/tests/unit/model/Model_STI.spec.ts
Labels: bug, documentation

#558 docs: fix typos + minor tweaks
  docs/content/1.guide/1.getting-started/1.quick-start.md
  docs/content/1.guide/2.model/1.getting-started.md
  docs/content/1.guide/2.model/2.accessors.md
  docs/content/1.guide/2.model/3.casts.md
  docs/content/1.guide/2.model/5.lifecycle-hooks.md
  docs/content/1.guide/2.model/6.pinia-options.md
  docs/content/1.guide/3.relationships/1.getting-started.md
  docs/content/1.guide/4.repository/2.retrieving-data.md
  docs/content/1.guide/4.repository/3.inserting-data.md
Labels: documentation

#562 fix(pinia-orm): delete on cascade doesn't work with n:m relations
  packages/pinia-orm/src/query/Query.ts
  packages/pinia-orm/tests/feature/repository/delete_with_relations.spec.ts
Labels: bug

#564 test(pinia-orm): number cast test with notNullable was not checking warning message
  packages/pinia-orm/src/model/attributes/types/Type.ts
  packages/pinia-orm/tests/unit/model/Model_Casts_Number.spec.ts
Labels: bug

#565 fix(pinia-orm): `null` is casted in DateCast
  packages/pinia-orm/src/model/casts/DateCast.ts
  packages/pinia-orm/tests/unit/model/Model_Casts_Date.spec.ts
Labels: bug

#583 fix(docs): release site not working
  docs/content/3.changelog.md
  docs/nuxt.config.ts
  docs/package.json
  docs/yarn.lock
Labels: documentation

#598 docs: typo in usage
  docs/content/1.guide/1.getting-started/2.usage.md
Labels: documentation

#625 fix(pinia-orm): Query constraints with nested relations in m:m relations broken
  packages/pinia-orm/src/model/attributes/relations/BelongsToMany.ts
  packages/pinia-orm/tests/feature/relations/constraints/constraints.spec.ts
Labels: bug

#636 feat(pinia-orm): Add the option to sort case insensitive with `sortBy`
  docs/content/2.api/1.composables/2.helpers/use-collect.md
  docs/content/2.api/1.composables/2.helpers/use-sort-by.md
  packages/pinia-orm/src/composables/collection/useCollect.ts
  packages/pinia-orm/src/composables/collection/useSortBy.ts
  packages/pinia-orm/src/support/Utils.ts
  packages/pinia-orm/tests/unit/composables/Use_Collect.spec.ts
Labels: enhancement

#638 docs(pinia-orm): Add requirements info for nuxt 2 users
  docs/content/1.guide/5.nuxt/1.setup.md
Labels: documentation

#652 docs: typo in example of quick-start.md
  docs/content/1.guide/1.getting-started/1.quick-start.md
Labels: documentation
