Repository CodeDredd/pinia-orm, pull requests merged in 2023-03, with the labels that each got.

#1047 docs: corrected spelling of 'recommended'
  docs/content/1.guide/1.getting-started/3.typescript.md
Labels: documentation

#1060 feat(pina-orm): Add `morphToMany` relation
  docs/content/1.guide/2.model/4.decorators.md
  docs/content/1.guide/3.relationships/5.polymorphic.md
  docs/content/2.api/2.model/1.options/2.fields-relations/morph-to-many.md
  packages/pinia-orm/package.json
  packages/pinia-orm/src/decorators.ts
  packages/pinia-orm/src/index.ts
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/model/attributes/relations/MorphToMany.ts
  packages/pinia-orm/src/model/decorators/attributes/relations/MorphToMany.ts
  packages/pinia-orm/tests/feature/relations/morph_to_many_retrieve.spec.ts
  packages/pinia-orm/tests/feature/relations/morph_to_many_save.spec.ts
  packages/pinia-orm/tests/feature/relations/morph_to_many_save_custom_key.spec.ts
Labels: enhancement

#1074 fix(pinia-orm): Types in hooks were conflicting
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/tests/feature/hooks/created.spec.ts
Labels: bug

#1066 feat(pinia-orm): Shared hydration cache & pinia actions triggering repo actions
  packages/pinia-orm/src/cache/SharedHydratedDatakCache.ts
  packages/pinia-orm/src/composables/useDataStore.ts
  packages/pinia-orm/src/composables/useRepo.ts
  packages/pinia-orm/src/composables/useStoreActions.ts
  packages/pinia-orm/src/query/Query.ts
  packages/pinia-orm/src/repository/Repository.ts
  packages/pinia-orm/tests/unit/composables/Use_Collect.spec.ts
  packages/pinia-orm/tests/unit/model/Model_Relations.spec.ts
  packages/pinia-orm/tests/unit/repository/Repository.spec.ts
Labels: enhancement

#1087 docs(pinia-orm): remove not correct await
  docs/content/1.guide/4.repository/5.deleting-data.md
Labels: documentation

#1100 feat(nuxt): Add improvements
  .github/workflows/ci.yml
  docs/content/1.guide/5.nuxt/1.setup.md
  packages/nuxt/build.config.ts
  packages/nuxt/package.json
  packages/nuxt/playground/models/User.ts
  packages/nuxt/playground/nuxt.config.ts
  packages/nuxt/src/module.ts
  packages/nuxt/src/runtime/plugin.vue2.ts
  packages/nuxt/src/runtime/plugin.vue3.ts
  packages/pinia-orm/package.json
  packages/pinia-orm/src/composables/useDataStore.ts
  packages/pinia-orm/src/index.ts
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/model/attributes/types/Uid.ts
  packages/pinia-orm/tsconfig.json
  playgrounds/nuxt3/package.json
  playgrounds/nuxt3/yarn.lock
  pnpm-lock.yaml
Labels: documentation, enhancement

#1107 feat(pinia-orm): Add the option for new not to persist the model
  docs/content/2.api/4.repository/make.md
  docs/content/2.api/4.repository/new.md
  packages/pinia-orm/src/query/Query.ts
  packages/pinia-orm/src/repository/Repository.ts
  packages/pinia-orm/tests/feature/hooks/creating.spec.ts
Labels: enhancement

#1121 fix(pinia-orm): Improve Date serialization in Model class
  packages/pinia-orm/src/model/Model.ts
Labels: enhancement

#1125 fix(pinia-orm): `$refresh()` is not working
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/tests/unit/model/Model.spec.ts
Labels: bug

#1136 fix(nuxt): Nuxt 3 throws error on build & dev
  packages/nuxt/build.config.ts
  packages/nuxt/package.json
  playgrounds/nuxt3/package.json
  playgrounds/nuxt3/yarn.lock
  pnpm-lock.yaml
Labels: bug
