Repository CodeDredd/pinia-orm, pull requests merged in 2023-09, with the labels that each got.

#1590 docs(pinia-orm-1382): Typo in docs examples: form -> from
  docs/content/1.guide/1.getting-started/4.typescript.md
Labels: documentation

#1596 docs(pinia-orm): Broken link or missing reference
  docs/content/1.guide/2.model/7.single-table-inheritance.md
Labels: documentation

#1510 feat: Add options for uid, nanoid/uid and uuid/uid
  docs/content/1.guide/2.model/1.getting-started.md
  docs/content/1.guide/2.model/4.decorators.md
  packages/pinia-orm/.eslintrc
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/model/attributes/types/Uid.ts
  packages/pinia-orm/src/model/casts/CastAttribute.ts
  packages/pinia-orm/src/model/decorators/Contracts.ts
  packages/pinia-orm/src/model/decorators/attributes/types/Uid.ts
  packages/pinia-orm/src/packages/nanoid/casts/AsyncCast.ts
  packages/pinia-orm/src/packages/nanoid/casts/DefaultCast.ts
  packages/pinia-orm/src/packages/nanoid/casts/NonSecureCast.ts
  packages/pinia-orm/src/packages/nanoid/decorators/Uid.ts
  packages/pinia-orm/src/packages/nanoid/decorators/UidAsync.ts
  packages/pinia-orm/src/packages/nanoid/decorators/UidNS.ts
  packages/pinia-orm/src/packages/uuid/casts/V1Cast.ts
  packages/pinia-orm/src/packages/uuid/casts/V4Cast.ts
  packages/pinia-orm/src/packages/uuid/decorators/UidV1.ts
  packages/pinia-orm/src/packages/uuid/decorators/UidV4.ts
  packages/pinia-orm/src/support/Utils.ts
  packages/pinia-orm/tests/setup.ts
  packages/pinia-orm/tests/unit/model/Model_Attrs_UID.spec.ts
  packages/pinia-orm/tests/unit/model/Model_Casts_Custom.spec.ts
  packages/pinia-orm/tests/unit/packages/nanoid/async_uid.spec.ts
  packages/pinia-orm/tests/unit/packages/nanoid/non_secure_uid.spec.ts
  packages/pinia-orm/tests/unit/packages/nanoid/uid.spec.ts
Labels: enhancement

#1206 feat: improve lookup performance and allow composite key lookup
  packages/pinia-orm/src/query/Query.ts
  packages/pinia-orm/tests/feature/repository/retrieves_find.spec.ts
Labels: enhancement

#1618 feat(pinia-orm): Add namespace option for the store
  .github/workflows/ci.yml
  docs/content/2.api/2.model/1.options/3.namespace.md
  docs/content/2.api/5.configuration.md
  package.json
  packages/nuxt/src/runtime/plugin.vue2.ts
  packages/nuxt/src/runtime/plugin.vue3.ts
  packages/pinia-orm/build.config.ts
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/query/Query.ts
  packages/pinia-orm/src/repository/Repository.ts
  packages/pinia-orm/src/store/Config.ts
  packages/pinia-orm/src/store/Store.ts
  packages/pinia-orm/tests/feature/repository/retrieves_has.spec.ts
  packages/pinia-orm/tests/feature/repository/retrieves_has_or.spec.ts
  packages/pinia-orm/tests/unit/PiniaORM.spec.ts
  packages/pinia-orm/tests/unit/model/Model_STI.spec.ts
Labels: bug, enhancement

#1648 fix(pinia-orm): `Uncaught TypeError: parent.$fields()[key] is undefied` when inserting nested data with polymorphic relationships
  packages/pinia-orm/src/schema/Schema.ts
  packages/pinia-orm/tests/feature/relations/morph_many_save.spec.ts
Labels: bug

#1627 docs: Update depencies & fix small display errors
  docs/app.config.ts
  docs/components/content/BackgroundLogo.vue
  docs/components/content/app/AgoliaDocSearch.client.vue
  docs/components/content/app/AppHeader.vue
  docs/components/content/landing/CardGrid.vue
  docs/components/content/layout/BasicLayout.vue
  docs/content/1.guide/1.getting-started/1.quick-start.md
  docs/content/1.index.md
  docs/nuxt.config.ts
  docs/package.json
  docs/server/api/search.ts
  docs/tailwind.config.ts
  docs/yarn.lock
Labels: documentation

#1603 feat: Add plugin system & axios plugin
  docs/components/content/app/AgoliaDocSearch.client.vue
  docs/content/1.guide/1.getting-started/2.usage.md
  docs/content/3.plugins/1.introduction.md
  docs/content/3.plugins/2.axios/1.guide/1.setup.md
  docs/content/3.plugins/2.axios/1.guide/2.configuration.md
  docs/content/3.plugins/2.axios/1.guide/2.usage.md
  docs/content/3.plugins/2.axios/1.guide/3.custom-actions.md
  docs/content/3.plugins/2.axios/2.api/1.repository.md
  docs/content/3.plugins/2.axios/2.api/2.request.md
  docs/content/3.plugins/2.axios/2.api/3.response.md
  docs/content/3.plugins/_dir.yml
  docs/content/4.changelog.md
  packages/axios/.eslintrc
  packages/axios/.gitignore
  packages/axios/LICENSE
  packages/axios/README.md
  packages/axios/build.config.ts
  packages/axios/package.json
  packages/axios/src/api/Request.ts
  packages/axios/src/api/Response.ts
  packages/axios/src/composables/useAxiosApi.ts
  packages/axios/src/composables/useAxiosRepo.ts
  packages/axios/src/index.ts
  packages/axios/src/plugin.ts
  packages/axios/src/repository/AxiosRepository.ts
  packages/axios/src/types/config.ts
  packages/axios/src/types/pinia-orm.ts
  packages/axios/test/feature/Request.spec.ts
  packages/axios/test/feature/Request_Actions.spec.ts
  packages/axios/test/feature/Request_DataKey.spec.ts
  packages/axios/test/feature/Request_DataTransformer.spec.ts
  packages/axios/test/feature/Request_Delete.spec.ts
  packages/axios/test/feature/Request_Save.spec.ts
  packages/axios/test/feature/Response_Delete.spec.ts
  packages/axios/test/feature/Response_Save.spec.ts
  packages/axios/test/helpers.ts
  packages/axios/test/setup.ts
  packages/axios/tsconfig.json
  packages/axios/vitest.config.ts
  packages/pinia-orm/package.json
  packages/pinia-orm/src/composables/useRepo.ts
  packages/pinia-orm/src/index.ts
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/repository/Repository.ts
  packages/pinia-orm/src/schema/Schema.ts
  packages/pinia-orm/src/store/Config.ts
  packages/pinia-orm/src/store/Plugins.ts
  packages/pinia-orm/src/store/Store.ts
  packages/pinia-orm/src/support/Utils.ts
  packages/pinia-orm/tests/feature/plugin/plugin.test.ts
  packages/pinia-orm/tests/feature/relations/eager_loads/eager_loads_all.spec.ts
  packages/pinia-orm/tests/helpers.ts
  packages/pinia-orm/tests/unit/PiniaORM.spec.ts
  pnpm-lock.yaml
Labels: enhancement

#1670 feat(pinia-orm): Throw an error when trying to save a list into a 1:1 relationship
  packages/pinia-orm/src/schema/Schema.ts
  packages/pinia-orm/tests/feature/relations/belongs_to_save.spec.ts
  packages/pinia-orm/tests/feature/relations/has_one_save.spec.ts
  packages/pinia-orm/tests/feature/relations/morph_one_save.spec.ts
  packages/pinia-orm/tests/feature/relations/morph_to_save.spec.ts
  packages/pinia-orm/tests/performance/prevent_rerender_of_child_components.spec.ts
  packages/pinia-orm/tests/performance/save_belongs_to_many_relation.spec.ts
  packages/pinia-orm/tests/performance/save_has_many_relation.spec.ts
  packages/pinia-orm/tests/performance/speed_find.spec.ts
Labels: enhancement

#1636 chore: Issue template improvement
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement

#1671 feat(pinia-orm): Composite primary key can now be used with `destroy` and `onDelete`
  packages/pinia-orm/src/model/Model.ts
  packages/pinia-orm/src/query/Query.ts
  packages/pinia-orm/tests/feature/repository/delete_with_relations.spec.ts
Labels: enhancement

#1681 fix(pinia-orm): proper exports for collection and uid helpers
  docs/content/1.guide/1.getting-started/1.quick-start.md
  docs/content/1.guide/1.getting-started/2.usage.md
  docs/content/1.guide/1.getting-started/4.typescript.md
  docs/content/1.guide/2.model/1.getting-started.md
  docs/content/1.guide/2.model/2.accessors.md
  docs/content/1.guide/2.model/4.decorators.md
  docs/content/1.guide/2.model/6.pinia-options.md
  docs/content/2.api/1.composables/2.helpers/use-collect.md
  docs/content/2.api/1.composables/2.helpers/use-group-by.md
  docs/content/2.api/1.composables/2.helpers/use-keys.md
  docs/content/2.api/1.composables/2.helpers/use-max.md
  docs/content/2.api/1.composables/2.helpers/use-min.md
  docs/content/2.api/1.composables/2.helpers/use-pluck.md
  docs/content/2.api/1.composables/2.helpers/use-sort-by.md
  docs/content/2.api/1.composables/2.helpers/use-sum.md
  docs/content/2.api/2.model/1.options/1.fields-attributes/attr.md
  docs/content/2.api/2.model/1.options/1.fields-attributes/boolean.md
  docs/content/2.api/2.model/1.options/1.fields-attributes/number.md
  docs/content/2.api/2.model/1.options/1.fields-attributes/string.md
  docs/content/2.api/2.model/1.options/1.fields-attributes/uid.md
  docs/content/2.api/2.model/1.options/2.fields-relations/belongs-to-many.md
  docs/content/2.api/2.model/1.options/2.fields-relations/belongs-to.md
  docs/content/2.api/2.model/1.options/2.fields-relations/has-many-by.md
  docs/content/2.api/2.model/1.options/2.fields-relations/has-many-through.md
  docs/content/2.api/2.model/1.options/2.fields-relations/has-many.md
  docs/content/2.api/2.model/1.options/2.fields-relations/has-one.md
  docs/content/2.api/2.model/1.options/2.fields-relations/morph-many.md
  docs/content/2.api/2.model/1.options/2.fields-relations/morph-one.md
  docs/content/2.api/2.model/1.options/2.fields-relations/morph-to-many.md
  docs/content/2.api/2.model/1.options/2.fields-relations/morph-to.md
  docs/content/2.api/2.model/1.options/3.casts.md
  docs/content/2.api/2.model/1.options/3.hidden.md
  docs/content/2.api/2.model/1.options/3.mutators.md
  packages/pinia-orm/package.json
Labels: bug
